# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: azure-faxe-cluster

steps:
- task: CopyFiles@2
  inputs:
    Contents: |
      **/*
      !todo
      !statefulset.yml
      !README.md
      !docker.run
      !Dockerfile_azedge
      !azure-pipelines.yml
      !azure-pipelines-devat.yml
      !azure-pipelines-azure.yml
      !azure-pipelines-helix.yml
      !docker-compose.yaml
      !Dockerfile_debian.intel-nuc
      !Dockerfile.intel-nuc
      !Dockerfile.k8s
      !Dockerfile_faxe
      !Dockerfile.revpi-core-3
      !docker-compose-devat.yml
      !docker-compose-helix.yml

    TargetFolder: '/opt/tgw/faxe_repo'
    CleanTargetFolder: true
    overWrite: true

- script: | 
    cd /opt/tgw/faxe_repo
    # gather azure build information:
    echo '$(Build.Repository.Name).$(Build.BuildNumber)'
    TAG=$(echo '$(Build.Repository.Name):$(Build.BuildNumber)')
    #build container-image
    #sudo -u faxe docker build -t $(Build.Repository.Name):$(Build.BuildNumber) -f Dockerfile_debian .
    # inject current build number into compose-file
    sed "s!Dockerfile_debian!$TAG!g" -i docker-compose-azure.yml
  displayName: 'build new image and tag it with azure pipeline build number'
#- script: |     
#    # stop old version
#    cd /opt/faxe/faxe_repo
#    sudo -u faxe /usr/local/bin/docker-compose -f docker-compose-azure.yml down
#    # kill/remove old data
#    if [[ $(sudo -u faxe docker ps -a | grep faxe ) ]]; 
#      then
#        sudo -u faxe /usr/bin/docker kill faxe; 
#        sudo -u faxe /usr/bin/docker container rm faxe;
#        #sudo -u faxe /usr/bin/docker rmi faxe_repo_faxe;
#        echo "running faxe found - kill+remove it"
#      else
#        echo "no running faxe found - skip"
#    fi
#  displayName: 'stop old container via docker-compose'    
#- script: |     
#    cd /opt/faxe/faxe_repo
#    sudo -u faxe /usr/local/bin/docker-compose -f docker-compose-azure.yml up -d
#  displayName: 'start container via docker-compose'