# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool: devat-faxe-cluster

steps:
- script: |
    docker-compose -f docker-compose-devat.yml down
    docker container kill faxe 2>/dev/null
    docker container rm faxe 2>/dev/null
  displayName: kill old app 
- task: CopyFiles@2
  inputs:
    Contents: |
      **/*
      !todo
      !statefulset.yml
      !README.md
      !docker.run
      !Dockerfile_azedge
      !azure-pipelines.yml
      !azure-pipelines-devat.yml
      !docker-compose.yaml

    TargetFolder: '/opt/faxe/faxe_repo'
    CleanTargetFolder: true
    overWrite: true

- script: | 
    docker-compose -f docker-compose-devat.yml  up -d
  displayName: 'start container via docker-compose'
  