# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'openshift-registry'
    repository: 'connected-warehouse-d/faxe'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile_k8s'
    tags: |
      $(Build.BuildId)
      $(Build.SourceBranchName)