# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- group: 'vcs_balena - ALL - secret' # variable group'
- name: BALENA_APPLICATION
  #value: 'TGW_DTR_TEST'
  value: 'MIAE-Test-Faxe'

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: 'checkout repo'
- script: |
    echo download balena cli
    #git clone https://github.com/balena-io/balena-cli.git
    
    wget https://github.com/balena-io/balena-cli/releases/download/v12.44.11/balena-cli-v12.44.11-linux-x64-standalone.zip
    unzip balena-cli-v12.44.11-linux-x64-standalone.zip
    cd balena-cli
    ./balena --version
  displayName: 'download balena cli'

- script: |
    echo extract access token from keyvault
    ./balena-cli/balena login --token $(echo $(BALENA-API-KEY))
    ./balena-cli/balena apps
  displayName: 'log into balena'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
  displayName: install docker cli



- script: |
    echo inject build number into docker-compose
  displayName: 'inject build number'

- script: |
    echo log into balena
  displayName: 'balena login'

- script: |
    echo push to balena
  displayName: 'balena push'
