trigger:
- none

variables:
- group: 'faxe_dev - Devcloud-keyvault' # variable group

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Setup
  jobs:
  - job:
    steps:
    - checkout: self
    - script: | 
        echo '$(Build.Repository.Name).$(Build.BuildNumber)'
        echo $(FAXE-CRATE-HTTP-PASS-KeyVault-Test)
    - task: Docker@2
      inputs:
        containerRegistry: 'nexus-docker-connection'
        repository: 'faxe'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile_debian'
        tags: |
           $(Build.BuildNumber)



