
variables:
- group: 'faxe_dev - Devcloud-keyvault' # variable group


stages:
- stage: Setup
  jobs:
  - job:
    steps:
    - checkout: self
    - script: | 
        echo '$(Build.Repository.Name).$(Build.BuildNumber)'
        echo $(FAXE-CRATE-HTTP-PASS-KeyVault-Test)



