version: '3.2'
services:
  faxe:
    # to have a fixed hostname for mnesia
    hostname: "faxe"
    image: "Dockerfile_debian"
    ports:
      - "8080:8080"
    container_name: faxe
    volumes:
      - /opt/faxe/docker_storage/mnesia:/data/mnesia
      - /opt/faxe/docker_storage/esq:/data/esq
      - /opt/faxe/docker_storage/python:/data/python
      - /opt/faxe/certs/running:/data/certs/
    env_file:
    - /opt/faxe/docker_storage/azure.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always