### Build stage 0
FROM erlang:22.3.4.2-alpine as base

RUN apk add git
RUN apk add build-base binutils

# Set working directory
RUN mkdir /buildroot
WORKDIR /buildroot

# Copy faxe application
RUN mkdir faxe
COPY ./rebar.config faxe/rebar.config

WORKDIR faxe

# And build the release
RUN rebar3 get-deps

COPY ./ .
RUN rebar3 as azedge release

### Build stage 1
FROM base

# Install some libs
RUN apk add openssl

ENV RELX_REPLACE_OS_VARS true

# Install the released application
COPY --from=base /buildroot/faxe/_build/azedge/rel/faxe /faxe

RUN mkdir /data
ENV MNESIA_DIR /data

# Expose relevant ports
## http api
EXPOSE 8081

ENTRYPOINT ["/faxe/bin/faxe"]
CMD ["foreground"]
