version: '2'
volumes:
  mnesia-data:
  esq-data:
services:
  faxe:
    hostname: "balena-faxe"
    build:
      context: "./"
      dockerfile: "Dockerfile.intel-nuc"
    ports:
      - "80:80"
    container_name: faxe
    volumes:
      - 'mnesia-data:/data/mnesia'
      - 'esq-data:/data/esq'
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always