version: '3.2'
services:
  faxe:
    # to have a fixed hostname for mnesia
    hostname: "faxe"
    build:
      context: "./"
      dockerfile: "Dockerfile_debian"
    ports:
      - "8080:8080"
    container_name: faxe
    volumes:
      - /opt/faxe/docker_storage/mnesia:/data/mnesia
      - /opt/faxe/docker_storage/esq:/data/esq
      - /opt/faxe/docker_storage/python:/data/python
    env_file:
    - /opt/faxe/docker_storage/devat.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always