version: '2'
volumes:
  mnesia-data:
  esq-data:
  python-data:
services:
  faxe:
    # to have a fixed hostname for mnesia
    hostname: "balena-faxe"
    image: template
    ports:
      - "80:80"
    container_name: faxe
    volumes:
      - 'mnesia-data:/data/mnesia'
      - 'esq-data:/data/esq'
      - 'python-data:/data/python'
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: always