### Build stage 0
FROM erlang:22.3.4.2-alpine as base

# Set working directory
RUN mkdir /buildroot
WORKDIR /buildroot

# Copy faxe application
COPY ./ faxe

WORKDIR faxe

# need git
RUN apk add git
RUN apk add build-base binutils

# And build the release
# TODO: RUN rebar3 with dependencies only (rebar3 get-deps)
RUN rebar3 as azedge release

### Build stage 1
FROM base

# Install some libs
RUN apk add openssl

ENV RELX_REPLACE_OS_VARS true

# Install the released application
COPY --from=base /buildroot/faxe/_build/azedge/rel/faxe /faxe
COPY --from=base /buildroot/faxe/DigiCertBaltimoreRoot.cer /faxe

RUN mkdir /data
ENV MNESIA_DIR /data

# Expose relevant ports
## http api
EXPOSE 8081

ENTRYPOINT ["/faxe/bin/faxe"]
CMD ["foreground"]
