kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: faxe-cluster
  labels:
    app: faxe-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faxe-cluster
  template:
    metadata:
      labels:
        app: faxe-cluster
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /v1/stats/vm
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: faxe
          livenessProbe:
            exec:
              command:
                - /faxe/bin/faxe
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: ERLANG_HOME
              value: /faxe
            - name: SCHEDULERS
              value: '4'
            - name: ERLANG_COOKIE
              value: '123456'
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: clustering
              containerPort: 25672
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: faxe-storage
              mountPath: /data
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: faxe-cm
          image: >-
            image-registry.openshift-image-registry.svc:5000/namespace/faxe:master
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - metadata:
        name: faxe-storage
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        volumeMode: Filesystem
  serviceName: faxe-cluster
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10