name: Erlang CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:25.3.2
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: git config --global url."https://".insteadOf git:// && rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
